#!/usr/bin/env node
/**
 * Regenerate `src/ipc/` from `schemas/*.eipc`.
 *
 * The environment matters: `PopoverOnly` in the schema has a `production` branch and a
 * `development` one, and which of the two is compiled in is decided *here*, at
 * generation time, not at runtime. A production build therefore does not contain the
 * loopback rule at all. That is also why generation is a `pre` step on dev, build,
 * check and test rather than something you run by hand — the output has to match the
 * thing you are about to run.
 *
 * Nothing in the generated code says which branch it holds except the validator body
 * itself, so this also writes `src/ipc/environment.ts`, exporting that choice as
 * `IPC_ENVIRONMENT`. The app compares it with `app.isPackaged` at startup, and it ends
 * up in the bundle beside the validator, where packaging looks for it.
 *
 * Usage: node scripts/generate-ipc.mjs [development|production]
 *
 * `EIPC_WIRING_FOLDER` redirects the output away from `src/ipc`, so a test can generate
 * development wiring without replacing the production wiring everything else reads.
 */
import { appendFile, readdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const env = process.argv[2] ?? process.env.EIPC_ENV ?? 'production'

if (env !== 'development' && env !== 'production') {
  console.error(
    `Unknown IPC environment ${JSON.stringify(env)}; expected development or production.`
  )
  process.exit(1)
}

// `wireValidator` reads this when it picks the validator branch, so it has to be set
// before the generator is imported and run.
process.env.EIPC_ENV = env

const { generateWiring } = await import('@marshallofsound/ipc')

/**
 * These three emit `import { SomeType }` / `export { SomeType }` for things that are
 * types, which this project's `verbatimModuleSyntax` and `noUnusedLocals` both reject.
 * Rather than loosen those flags for the whole codebase, opt exactly these out. The
 * `src/ipc/<layer>/*.ts` wrappers the app actually imports, the shared browser runtime,
 * the generated renderer client and the `common-runtime` module that imports our Zod
 * schemas by name are all left checked — so a schema referencing an export that
 * `src/shared/schemas.ts` does not have still fails the type-check.
 *
 * If the generator later trips a strict flag somewhere else, that should show up as a
 * loud failure here rather than being pre-emptively silenced.
 */
const UNCHECKED = ['common', 'browser', 'preload']

/** @param {string} folder */
async function silenceInternals(folder) {
  const entries = await readdir(folder, { recursive: true, withFileTypes: true })
  await Promise.all(
    entries
      .filter((entry) => entry.isFile() && entry.name.endsWith('.ts'))
      .map(async (entry) => {
        const file = join(entry.parentPath, entry.name)
        const source = await readFile(file, 'utf8')
        if (source.startsWith('// @ts-nocheck')) return
        await writeFile(file, `// @ts-nocheck\n${source}`)
      })
  )
}

/**
 * Typed as the union, not the literal: with a literal type, the startup check comparing
 * it against the other environment would not type-check at all.
 * @param {'development' | 'production'} environment
 */
function environmentModule(environment) {
  return `// Generated by scripts/generate-ipc.mjs. Do not edit.
//
// Which branch of the environment-dependent \`PopoverOnly\` validator this wiring
// contains. It is decided at generation time, so the app compares it with
// \`app.isPackaged\` at startup, and packaging refuses a build that says 'development'.
export const IPC_ENVIRONMENT = '${environment}' as 'development' | 'production'
`
}

const wiringFolder = process.env.EIPC_WIRING_FOLDER
  ? resolve(process.env.EIPC_WIRING_FOLDER)
  : resolve(root, 'src/ipc')

try {
  // `generateWiring` deletes the folder before writing, so an `environment.ts` from an
  // earlier run can never outlive the wiring it described.
  await generateWiring({ schemaFolder: resolve(root, 'schemas'), wiringFolder })
  await Promise.all(
    UNCHECKED.map((layer) => silenceInternals(join(wiringFolder, '_internal', layer)))
  )
  await writeFile(join(wiringFolder, 'environment.ts'), environmentModule(env))
  // The marker is EIPC's, and it only checks that the file exists; the extra line is for
  // a person asking which wiring is in there.
  await appendFile(join(wiringFolder, '.eipc-generated'), `Environment: ${env}\n`)
  const shown = relative(root, wiringFolder)
  console.log(`Generated ${shown.startsWith('..') ? wiringFolder : shown} for ${env}.`)
} catch (error) {
  console.error(
    'Could not generate the IPC wiring:',
    error instanceof Error ? error.message : error
  )
  process.exit(1)
}
